# Generated by Django 3.2.10 on 2022-04-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
