# Generated by Django 3.2.10 on 2022-04-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_crypto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='last_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='last_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
