# Generated by Django 3.2.10 on 2022-04-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20220414_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
