# Generated by Django 3.2.10 on 2022-04-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_crypto_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
